[package]
name = "rust_vault"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.8", features = ["derive"] }
crossterm = "0.27.0"
error-chain = "0.12.4"
rust-fuzzy-search = "0.1.1"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.120"
